---
name: black

on:
  push:
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/black.yaml"
  pull_request:
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/black.yaml"

jobs:
  black:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run black formatter checks
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
          # TODO: remove this once passing
          fail_on_error: false
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
