---
name: test_pip

on:
  push:
    paths:
      - "setup.cfg"
      - "requirements.txt"
      - ".github/workflows/test_pip.yaml"
  pull_request:
    paths:
      - "setup.cfg"
      - "requirements.txt"
      - ".github/workflows/test_pip.yaml"

# https://github.com/actions/setup-python
jobs:
  test_pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version: ['3.5', '3.8', '3.9']
        exclude:
          # exclude versions github doesn't have runners for:
          - os: macos-latest
            python-version: '3.4'
          - os: ubuntu-latest
            python-version: '3.1'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: pip install self
        run: pip install generate-bes-from-template
      - name: Run Tests
        run: python tests/tests.py --test_pip
